"""sync current models

Revision ID: 6ee2c07ed1ff
Revises: 648d963688dd
Create Date: 2026-06-06 20:03:49.705556

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6ee2c07ed1ff'
down_revision: Union[str, Sequence[str], None] = '648d963688dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
